export const ComponentIDs = {
  addProjectFormDescription: 'addProjectFormDescription',
  addProjectFormHomePage: 'addProjectFormHomePage',
  addProjectFormInterests: 'addProjectFormInterests',
  addProjectFormName: 'addProjectFormName',
  addProjectFormParticipants: 'addProjectFormParticipants',
  addProjectFormPicture: 'addProjectFormPicture',
  addProjectFormSubmit: 'addProjectFormSubmit',
  addProjectMenuItem: 'addProjectMenuItem',
  artistsMenuItem: 'artistsMenuItem',
  basicNavbarNav: 'basicNavbarNav',
  browseArtistsFilterButton: 'browseArtistsFilterButton',
  browseGigsFilterButton: 'browseGigsFilterButton',
  browseGigsFilterForm: 'browseGigsFilterForm',
  createJamSession: 'createJamSession',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  filterFormInterests: 'filterFormInterests',
  filterFormSubmit: 'filterFormSubmit',
  filterMenuItem: 'filterMenuItem',
  homeFormBio: 'homeFormBio',
  homeFormFirstName: 'homeFormFirstName',
  homeFormLastName: 'homeFormLastName',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',
  interestsMenuItem: 'interestsMenuItem',
  jamSessionsMenuItem: 'jamSessionsMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormVerifyPassword: 'signUpFormVerifyPassword',
  signUpFormSubmit: 'signUpFormSubmit',
};

export const PageIDs = {
  addProjectPage: 'addProjectPage',
  browseArtistsPage: 'browseArtistsPage',
  browseGigsPage: 'browseGigsPage',
  createJamSessionPage: 'CreateJamSessionPage',
  filterPage: 'filterPage',
  homePage: 'homePage',
  interestsPage: 'interestsPage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  profilesPage: 'profilesPage',
  projectsPage: 'projectsPage',
  signInPage: 'signInPage',
  signUpPage: 'signUpPage',
  signOutPage: 'signOutPage',
  viewProfile: 'ViewProfile',
};
